### ISSUE TITLE
Erstellung einer Liste benötigter Assets für das UI

### ISSUE THREAD

**Issue by djb12** [PSMGGamesSS2015/PSMG_SS_2015_RTS_GameGroup#19]

**Comment by torjin** [comment]
9 Buttons für Berufe + 1 Button "Arbeitslos" Buttons mit Beschriftung und/oder Bild/Symbol?
(Rest)zeit? 
"Aufgeben"-Button?

**Comment by djb12** [comment]
siehe Wiki-Artikel
